<?php

namespace saso\util;

/**
 * Companion to {@see EnvLoader}: rewrites a single key in a `.env` file
 * preserving every other line. Used by the installer bootstrap path to
 * fill in an auto-generated APP_KEY when the user opens /installer/start
 * on a fresh deployment without ever needing to edit the file by hand.
 *
 * Intentionally minimal — no quoting, no escaping. Callers are expected
 * to pass safe single-line strings. Generated secrets (base64 / hex
 * random output) satisfy that constraint.
 */
final class EnvWriter
{
    /**
     * Set $key to $value in the file at $path. Appends a new line if the key
     * is not already present. Returns true on a successful write.
     *
     * If the file does not exist, it is created (the directory must already
     * be writable). This lets the installer bootstrap a fresh `.env` from
     * scratch on first run.
     */
    public static function set(string $path, string $key, string $value): bool
    {
        if (!preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $key)) {
            return false;
        }

        if (!is_file($path)) {
            $dir = dirname($path);
            if (!is_dir($dir) || !is_writable($dir)) {
                return false;
            }
            $created = file_put_contents(
                $path,
                "# SASO — generated by installer wizard\n",
                LOCK_EX,
            );
            if ($created === false) {
                return false;
            }
            @chmod($path, 0640);
        }

        if (!is_writable($path)) {
            return false;
        }

        $contents = file_get_contents($path);
        if ($contents === false) {
            return false;
        }

        $sanitised = self::sanitiseValue($value);
        $line      = $key . '=' . $sanitised;
        $pattern   = '/^' . preg_quote($key, '/') . '=.*$/m';

        if (preg_match($pattern, $contents)) {
            $updated = preg_replace($pattern, $line, $contents, 1);
        } else {
            $updated = rtrim($contents, "\n") . "\n" . $line . "\n";
        }

        return file_put_contents($path, $updated, LOCK_EX) !== false;
    }

    /**
     * Convenience: apply multiple key/value pairs. Returns true only when
     * every write succeeds (writes that came before a failure are not
     * rolled back — the file is left in the best-effort partial state).
     *
     * @param array<string, string> $values
     */
    public static function setMany(string $path, array $values): bool
    {
        $ok = true;
        foreach ($values as $key => $value) {
            $ok = self::set($path, $key, $value) && $ok;
        }
        return $ok;
    }

    /**
     * Quote the value if it contains characters that would otherwise change
     * how {@see EnvLoader::loadFile()} parses the line (whitespace, `#`,
     * `"`, `'`). Bare alphanumeric / DSN-like strings are passed through.
     */
    private static function sanitiseValue(string $value): string
    {
        // Strip newlines defensively — the install wizard validates inputs,
        // but if anything slipped through it would otherwise corrupt the file.
        $value = str_replace(["\r", "\n"], '', $value);

        $needsQuotes = preg_match('/[\s"#\'\\\\]/', $value) === 1;
        if (!$needsQuotes) {
            return $value;
        }

        $escaped = str_replace(['\\', '"'], ['\\\\', '\\"'], $value);
        return '"' . $escaped . '"';
    }
}
