<?php

declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

/**
 * Creates the `pairing_code` table — short-lived QR pairing tokens.
 *
 * A pairing code is generated by an admin and encoded into a QR code URI
 * (`saso://connect?token=<RAW>&url=<SERVER>`). The Flutter app scans the QR,
 * extracts the raw token, and exchanges it at POST /api/v1/mobile/connect for
 * a long-lived DeviceToken. Once exchanged, `used` is set to 1. Expired and
 * used rows are cleaned up by a periodic cron sweep.
 *
 * Only the SHA-256 hash of the raw token is stored so a DB leak cannot be
 * replayed. TTL is 10 minutes (enforced in PHP via `expires_at`).
 *
 * Reversible: `down()` drops the table.
 */
final class CreatePairingCode extends AbstractMigration
{
    public function up(): void
    {
        $this->table('pairing_code', [
            'id'        => 'id',
            'engine'    => 'InnoDB',
            'collation' => 'utf8mb4_unicode_ci',
            'comment'   => 'Short-lived QR pairing codes for Flutter device onboarding.',
        ])
            ->addColumn('token_hash', 'string', [
                'limit'   => 64,
                'null'    => false,
                'comment' => 'SHA-256 hex digest of the raw URL-safe base64 token.',
            ])
            ->addColumn('label', 'string', [
                'limit'   => 200,
                'null'    => false,
                'comment' => 'Human-readable description (e.g. device name or purpose).',
            ])
            ->addColumn('used', 'boolean', [
                'null'    => false,
                'default' => 0,
                'comment' => '1 = already exchanged for a DeviceToken.',
            ])
            ->addColumn('expires_at', 'datetime', [
                'null'    => false,
                'comment' => 'UTC expiry; reject attempts after this timestamp.',
            ])
            ->addColumn('created_at', 'datetime', [
                'null' => false,
            ])
            ->addIndex(['token_hash'], ['unique' => true, 'name' => 'uniq_pairing_token_hash'])
            ->addIndex(['expires_at'], ['name' => 'idx_pairing_expires_at'])
            ->create();
    }

    public function down(): void
    {
        $this->table('pairing_code')->drop()->update();
    }
}
